import express from 'express';
import pg from 'pg';
import crypto from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {Pool}=pg; const app=express(); app.use(express.json({limit:'12mb'}));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('render.com')?{rejectUnauthorized:false}:false});
const sessions=new Map();
const hash=p=>crypto.scryptSync(p,process.env.AUTH_SALT||'couple-universe-change-me',32).toString('hex');
async function db(q,p=[]){return (await pool.query(q,p)).rows}
async function init(){await db(`create table if not exists cu_users(id serial primary key,email text unique not null,password_hash text not null,name text not null,created_at timestamptz default now()); create table if not exists cu_spaces(id serial primary key,invite text unique not null,created_at timestamptz default now()); create table if not exists cu_members(space_id int references cu_spaces(id) on delete cascade,user_id int references cu_users(id) on delete cascade,primary key(space_id,user_id)); create table if not exists cu_memories(id serial primary key,space_id int references cu_spaces(id) on delete cascade,title text not null,body text not null,date date not null,created_at timestamptz default now()); create table if not exists cu_annivs(id serial primary key,space_id int references cu_spaces(id) on delete cascade,title text not null,date date not null,note text default ''); create table if not exists cu_letters(id serial primary key,space_id int references cu_spaces(id) on delete cascade,to_name text not null,body text not null,sign text not null,date date not null); create table if not exists cu_moods(id serial primary key,space_id int references cu_spaces(id) on delete cascade,user_id int references cu_users(id) on delete cascade,mood text not null,date date not null,unique(space_id,user_id,date)); create table if not exists cu_messages(id serial primary key,space_id int references cu_spaces(id) on delete cascade,user_id int references cu_users(id) on delete cascade,body text not null,created_at timestamptz default now()); create table if not exists cu_photos(id serial primary key,space_id int references cu_spaces(id) on delete cascade,title text not null,data text not null,date date not null,created_at timestamptz default now())`)}
function token(){return crypto.randomBytes(32).toString('hex')}
async function auth(req,res,next){const u=sessions.get(req.get('authorization')?.replace('Bearer ','')||req.cookies?.cu);if(!u)return res.status(401).json({error:'请先登录'});req.user=u;next()}
app.use((req,res,next)=>{const c=req.headers.cookie||'';req.cookies=Object.fromEntries(c.split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}));next()});
app.post('/api/register',async(req,res)=>{try{const {email,password,name}=req.body;if(!email||!password||!name||password.length<6)return res.status(400).json({error:'邮箱、昵称和至少6位密码均必填'});let rows=await db('select id from cu_users where email=$1',[email.toLowerCase()]);if(rows.length)return res.status(409).json({error:'这个邮箱已经注册'});const u=(await db('insert into cu_users(email,password_hash,name) values($1,$2,$3) returning id,email,name',[email.toLowerCase(),hash(password),name]))[0];const invite='LOVE-'+crypto.randomBytes(3).toString('hex').toUpperCase();const s=(await db('insert into cu_spaces(invite) values($1) returning id,invite',[invite]))[0];await db('insert into cu_members(space_id,user_id) values($1,$2)',[s.id,u.id]);const t=token();sessions.set(t,u.id);res.cookie?.('cu',t);res.json({token:t,user:u,space:s})}catch(e){res.status(500).json({error:'注册失败'})}});
app.post('/api/login',async(req,res)=>{const {email,password}=req.body;const u=(await db('select id,email,name from cu_users where email=$1 and password_hash=$2',[email?.toLowerCase(),hash(password||'')]))[0];if(!u)return res.status(401).json({error:'邮箱或密码错误'});const t=token();sessions.set(t,u.id);const s=(await db('select s.* from cu_spaces s join cu_members m on m.space_id=s.id where m.user_id=$1 order by s.id limit 1',[u.id]))[0];res.json({token:t,user:u,space:s||null})});
app.post('/api/join',auth,async(req,res)=>{const s=(await db('select * from cu_spaces where invite=$1',[String(req.body.invite||'').toUpperCase()]))[0];if(!s)return res.status(404).json({error:'邀请码不存在'});await db('insert into cu_members(space_id,user_id) values($1,$2) on conflict do nothing',[s.id,req.user]);res.json({space:s})});
app.get('/api/me',auth,async(req,res)=>{const u=(await db('select id,email,name from cu_users where id=$1',[req.user]))[0];const s=(await db('select s.* from cu_spaces s join cu_members m on m.space_id=s.id where m.user_id=$1 limit 1',[req.user]))[0];res.json({user:u,space:s||null})});
async function sid(req){return (await db('select space_id from cu_members where user_id=$1 limit 1',[req.user]))[0]?.space_id}
app.get('/api/data',auth,async(req,res)=>{const s=await sid(req);if(!s)return res.status(400).json({error:'还没有情侣空间'});const [memories,annivs,letters,moods,messages,photos,members]=await Promise.all([db('select id,title,body,date from cu_memories where space_id=$1 order by date desc,id desc',[s]),db('select id,title,date,note from cu_annivs where space_id=$1 order by date',[s]),db('select id,to_name as "to",body,sign,date from cu_letters where space_id=$1 order by date desc,id desc',[s]),db('select m.*,u.name from cu_moods m join cu_users u on u.id=m.user_id where m.space_id=$1 order by date desc,id desc',[s]),db('select m.id,m.body,m.created_at,u.name from cu_messages m join cu_users u on u.id=m.user_id where m.space_id=$1 order by m.id desc limit 100',[s]),db('select id,title,data,date from cu_photos where space_id=$1 order by date desc,id desc',[s]),db('select u.id,u.name,u.email from cu_members m join cu_users u on u.id=m.user_id where m.space_id=$1',[s])]);res.json({memories,annivs,letters,moods,messages:messages.reverse(),photos,members,space_id:s})});
app.post('/api/memories',auth,async(req,res)=>{const s=await sid(req);const {title,body,date}=req.body;if(!s||!title||!body)return res.status(400).json({error:'内容不完整'});res.json({item:(await db('insert into cu_memories(space_id,title,body,date) values($1,$2,$3,$4) returning *',[s,title,body,date]))[0]})});
app.post('/api/annivs',auth,async(req,res)=>{const s=await sid(req);const {title,date,note=''}=req.body;if(!s||!title||!date)return res.status(400).json({error:'内容不完整'});res.json({item:(await db('insert into cu_annivs(space_id,title,date,note) values($1,$2,$3,$4) returning *',[s,title,date,note]))[0]})});
app.post('/api/letters',auth,async(req,res)=>{const s=await sid(req);const {to,body,sign,date}=req.body;if(!s||!body)return res.status(400).json({error:'正文不能为空'});res.json({item:(await db('insert into cu_letters(space_id,to_name,body,sign,date) values($1,$2,$3,$4,$5) returning *',[s,to||'最喜欢的你',body,sign||'爱你的人',date]))[0]})});
app.post('/api/moods',auth,async(req,res)=>{const s=await sid(req);const {mood,date}=req.body;await db('insert into cu_moods(space_id,user_id,mood,date) values($1,$2,$3,$4) on conflict(space_id,user_id,date) do update set mood=excluded.mood',[s,req.user,mood,date]);res.json({ok:true})});
app.post('/api/messages',auth,async(req,res)=>{const s=await sid(req);const body=String(req.body.body||'').trim();if(!s||!body)return res.status(400).json({error:'消息不能为空'});res.json({item:(await db('insert into cu_messages(space_id,user_id,body) values($1,$2,$3) returning id,body,created_at',[s,req.user,body]))[0]})});
app.post('/api/photos',auth,async(req,res)=>{const s=await sid(req);const {title,data,date}=req.body;if(!s||!data)return res.status(400).json({error:'请选择照片'});if(data.length>8*1024*1024)return res.status(413).json({error:'照片太大，请压缩到8MB以内'});res.json({item:(await db('insert into cu_photos(space_id,title,data,date) values($1,$2,$3,$4) returning id,title,date',[s,title||'我们的照片',data,date]))[0]})});
app.get('/api/health',async(_,res)=>{try{await db('select 1');res.json({ok:true})}catch{res.status(500).json({ok:false})}});
const __dirname=path.dirname(fileURLToPath(import.meta.url));app.use(express.static(path.join(__dirname,'public')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));init().then(()=>app.listen(process.env.PORT||10000,'0.0.0.0')).catch(e=>{console.error(e);process.exit(1)});
